branches:
  only:
    - master
    - /^(fix|feature|dev)\/\w+$/
language: node_js
node_js:
  - "node"
sudo: false
install:
  - npm install
  - npm install -g codecov
script:
  - npm test
  - cross-env NODE_ENV=test nyc npm test
  - codecov
