branches:
  only:
    - master
    - /^(fix|feat|feature|dev|tmp)\//
language: node_js
node_js:
  - "node"
env:
  global:
    - secure: "c1lm6f1Prd+Kgy2Wsv5gyUADz009GPNiZGL6tLT7qNNEeuC5Lpq8TfZfM++gcz/eURNWbBkhs/yR9/TRzvvv3fab81AdCDyOW3t9/9W2GWu75CrMNqOroINEJx4PrN1rgxeosfPGRMqi4kCBGLM3ot/LxjFyKywz3Zlp/PK40K+Aq3oej8DIxOc6nq857UAJ62U3PM2eKVajMCE/DsPK1gGWqdVPb4fsfLUeEgEuWYNkDt8P5Ayt7QuO4fd02shGiJGGZFlIJqx8M9dTwKHAjqeQdIRbPdE/93F3q5Wr25QrMpz0tv9KQW+QLeN5tij5/RsJ7/Bk1Hjj+X0CH8ljiS636h5ITH83pG6YrqlaRmT+FQdHCmPfP9z6RkC1uvfft2N72SkiQigEobtkDd0xJIQ3zvuQL7r/XDyqm0lEEOGkiKQmXPNRgK+sqm71+aU/rSI4X3YwmPAXGP+tL+khBaBahpEqHzfDsIoXGcrOroBP4Jo7DzvRSMPSkowuQZVguzPS38DQ2vljJQKe2j7gnxxND1acjLnqMLNDkwino80/PlNBqmHTEz8ofpKNXnI2lMvSHy3p00hz1aTH+GZKqb6RlUBtI3SVmW4fKs4j86IJnX7vr7dClQmG5JFyAOSdovTSTiexErwIRDCf9xTVsp3SUj4bW2pEUj7rQHONiXM="
    - secure: "KOI/25hBK0FYxsHd+97d1JIfozbzPlDLS3wJqGseXC2nrC9LIyk/E2t6ZVBDqy5lV/LBCUjzq+MpVg2Njb/VtyvbPmuSGrFfG1HXWACmcjuEYrmRwY+6lrn6+ZYHNO8wXfVPMeJ2HHYWwGB+NrupIBLZGtKRRiDGF/b9C62eBvgcViYTihnLcHUyLOHGq050WI5S7T6DoM05s0efA9f5cMy2PTSt9VZ4ixjixszklWanJszsxrcHKosYqHpfW6kvO1CJSz1TABOkPv59uwN+pKrAi6OZzmKloYLVz3qAXtwwJZlLsQpKcRRJUgyTpccmCdSDydClM13/n3/1FXrseTEuI5cry/UVBBQjqKS0+DSS3vzL9d4qdqKJBWsm8hDu7J65hiK5mXjYlGygW1XFjfHaG2EhCc9HNoFi4PZHt3ilA1KdUloclHkynpiaIKIIfErXV9J6dg8p68qRrsFqsVZvwyc4jDFBZs7EcpB0kw1HOnP+e8VS6excIyU5xlnSoxMA1zSt3Qgxt32YkK/FkHi1YY05QQu7pdnZ6tB4HDq3uoBMVwoV0bDq9CvUdsutDtsuPP+FJ5TkVmkS8bGpesMlafA9GFm0JI5l2w6qLS6Pf2jbg6BjyKc2zcV4+oTTd+zWMKrgSPxaRLng1aFNUQdXJ/tBiwNGK4Zb3ZXckIM="
sudo: false
install:
  - npm install
  - npm install -g codecov
  - mkdir build
script:
  - npm run coverage && codecov
  - "npm run dist:main && npm run dist:test"
  - "npm run test:browser"
